### ISSUE TITLE
Database/API Epic

### ISSUE THREAD

**Issue by codemonkey800** [codemonkey800/cs160-food-project#36]
The database and APIs are external web services managed by AWS. A lot has to be done for the database, so I'm creating an epic for this:

- [ ] #21 Determine store locations
- [ ] #22 Create API for order resource
- [ ] #23 Create API for tracking resource
- [ ] #24 Create API for product resource
- [ ] #25 Integrate database queries into AWS lambda functions
- [ ] #26 Query to add tracking information
- [ ] #27 Query to add order information
- [ ] #28 Query to update tracking information
- [ ] #29 Query to update product data
- [ ] #30 Query to retrieve tracking information
- [ ] #31 Query to retrieve order informationdat
- [ ] #32 Query to retrieve product data
- [ ] #33 Create PRODUCT, ORDER, ORDERINFO, TRACKINFO tables
- [ ] #34 Get database connection established
