### ISSUE TITLE
Server Epic

### ISSUE THREAD

**Issue by codemonkey800** [codemonkey800/cs160-food-project#37]
Aside from hosting the client bundle and pre-fetching data, server side rendering, and other client side related stuff, the server is also responsible for additional functionality and data processing. There's a lot of work to do for the server, so I'm creating an epic:

- [ ] #7 Implement DisplayDeliveries() function
- [ ] #8 Implement EndDelivery() function
- [ ] #9 Implement StartDelivery() function
- [ ] #11 Implement track order function
- [ ] #13 Install and configure apache web server on ec2 instance
- [ ] #14 Create http request to retrieve tracking and order numbers
- [ ] #15 Create http request to update product quantities in database
- [ ] #16 Create http request to verify products in shopping cart are still available for purchase
- [ ] #17 Create http request to verify credit card information
- [ ] #18 Verify Credit Card Numbers
