### ISSUE TITLE
Cleanup backup-web branch

### ISSUE THREAD

**Issue by codemonkey800** [codemonkey800/cs160-food-project#43]
## Description
Right now there's a backup-web branch that includes an HTML5 and CSS3 template for eCommerce. This is reserved for case where the React.js app can't be finished in time. Hopefully it won't come to that, but it's better to have a backup.

The backup branch is located at: https://github.com/codemonkey800/cs160-food-project/tree/backup-web

## Todo
There's a lot of boilerplate and random trash inside the template, and we don't need all of the functionality included in the template.

- [ ] Remove JQuery
  - [ ] Use alternative, non-JQuery plugins
- [ ] Remove unused UI components
- [ ] Implement client
  - [ ] Use [AJAX](https://developer.mozilla.org/en-US/docs/AJAX) and [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) to interact with backend
  - [ ] Use a smaller web framework to manage state and UI management. Here are possible some options:
    - [Backbone.js](http://backbonejs.org/)
    - [Ember.js](https://emberjs.com/)
    - [Knockout.js](http://knockoutjs.com/)
    - Plain JS (This will suck the most)

## Rationale for removing JQuery
JQuery is great and it filled in a gap present in JavaScript web apps in the past. However, it's value is not what it was. JQuery was designed to provide access to cross-browser APIs that would handle all of the idiosyncrasies present in different browsers. This is no longer a problem since most modern browsers now try to follow web standards.

Here's a good doc on why we most likely won't need JQuery for the web app: [You Don't Need JQuery](https://github.com/oneuijs/You-Dont-Need-jQuery).

Of course, this all depends on various factors, and hopefully we won't have to use the template at all.

## Caveat
Since we're working with a regular old static-ish HTML, JS, and CSS template, even though a lot of the visuals are readily available, the core code may or may not fit our needs. Depending on what's provided and what needs to be removed from the template, it might be actually more work to get everything in the template working for us.
