### ISSUE TITLE
Configure SSR for Material UI and Koa.js/Next.js

### ISSUE THREAD

**Issue by codemonkey800** [codemonkey800/cs160-food-project#44]
## Description
A key feature of the web app is its ability to pre-render React.js views and serve them as static markup for initial page loads. This is beneficial for many reasons:

### Faster client side load times
One of the inherent problems with non-ssr Single Page Application (SPA) web apps is that clients not only have to spend time downloading all of the necessary files, but they also have to spend some time loading the app. Bigger and complex apps usually require more time to bootstrap, and might be a lot slower on the client, especially for mobile users.

Rendering everything on the server for the initial page load is great because it handles the majority of the heavy lifting on the server side and then the rest is handled on the client.

### Improved SEO
The nature of our web app, as well as most modern web apps, are often asynchronous in nature. That is, the web app could be making various HTTP requests or perform background actions. This is fine for a client since the browser should be able to handle everything fine.

Search Engine Optimization (SEO) affects the visibility of web apps in search engine indexers. Asynchronous JavaScript web apps suck hard when it comes to indexers, and in fact may not even work at all. Client browsers can render the web apps fine because it handles all of the background activity in a web app, but an indexer might be less sophisticated than a web browser.

With SSR, we can render the web app into simple HTML and CSS that search engine indexers will be able to use for SEO.

### Extract CSS stylesheets on server and load it into initial HTML
An issue with dynamically created CSS or CSS-in-JS solutions is that prior to the CSS being ready, a user may encounter what's known as the dreaded Flash Of Unstyled Content, or FOUC. This is when the entire structure of the app is visibly shown, but the styling isn't ready yet, resulting in a flash of just plain HTML content.

With SSR, we can extract the CSS from React.js components and place them into their own global stylesheet that we can provide with the initial render. That way, we can avoid FOUC. The client will remove the global stylesheet as soon as the client side styling is finished rendering.

## Todo
- [ ] Render React components on the server
  - [ ] Implement Koa.js middleware to render app to static markup
  - [ ] Pass rendered markup into Next.js
- [ ] Remove FOUC
  - [ ] Extract CSS stylesheets from rendered components
  - [ ] Include CSS stylesheet as part of initial render for Next.js

## Resources
Some useful resources for this issue is actually included in the documentation of Material UI and Next.js, notably:

- [Material UI SSR](https://material-ui-1dab0.firebaseapp.com/#/getting-started/server-rendering)
- [Custom Server Logic with Koa.js](https://github.com/zeit/next.js/tree/master/examples/custom-server-koa)

**Comment by codemonkey800** [comment]
Switched to nwb which compiles the website down to a regular static website. Closing this issue since it's useless now.
